### PR TITLE
update dates and title-doc number

### PR DESCRIPTION
**Pull request by PalmJanssen**
Updated status dates and doc number. Is this okay as it is?

### CODE REVIEW

**Comment by cportele** [comment]
@PalmJanssen - The document number must be set in `document.adoc`, `document.html` must be derived using metanorma. I have reverted your change and updated the adoc file.

@jechterhoff - Can you update the HTML?

**Comment by jechterhoff** [comment]
Done

**Comment by PalmJanssen** [comment]
aha, thought that we would not run metanorma, but you're right that this is the proper way. I see that submission/publication date and (24-017r1) do not show up in the title. Is that okay?

**Comment by cportele** [comment]
@PalmJanssen - The dates are set by OGC before publication. And yes, the OGC document number is not part of the document title.

**Pull request merged**
